version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_NAME: 'Production'
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py seeds &&
             python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: ${DEFAULT_DATABASE_DSN}
    env_file:
      - ./.env
